### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Narjhanam** [SahAssar/bolt-sahassar-extras#1]
Hello,

I just saw this extension, I wanted to ask, is it possible to modify the way dashboard look and the widgets that contains using this extension, whitout modifying any of the core files?

Cheers,

**Comment by SahAssar** [comment]
Hey Narjhanam,

This is a quick overview of how you can modify the dash:

In the normal bolt you can:
 - add widgets to the dashboard via extensions, 
 - remove certain parts of the dashboard (the stack and the newsfeed) via your main configuration, 
 - customize backend listings via putting templates in the /app/view/twig/custom/listing folder.

The extension does a few additional things:
 - moves the /app/view/twig/custom/listing to a place that is not tracked by git (/app/config/backend/listing) and adds an easier way to reach it from the web interface, 
 - Adds options to change colors in the header and navigation,
 - Adds an option to change the logo on the login screen
 - Adds options to setup shortcuts to commonly used theme files.

Besides these things you will have to modify the core files as far as I know. Here is an example just using this extension and bolt's own options:

![example](https://cloud.githubusercontent.com/assets/5096632/9602316/b5eb63ee-50a7-11e5-94ec-7a832f6bb61f.png)

Does that answer your question? :smiley:

**Comment by Narjhanam** [comment]
Hey SahAssar,

Thanks for quick reply, yeah it does. I'll test your extension and learn from it :smile: 
Just for clarification, can I for example  add a widget that display the number of items, or post or ... or a chart... something like that :
![4444444444](https://cloud.githubusercontent.com/assets/12384290/9602548/462dacb4-50b2-11e5-8969-861fc729d09b.png)

Can I do it by writing an extension(s) for it ?

**Comment by SahAssar** [comment]
Yeah, but your widget can only be placed in the right sidebar. If you want to make a widget look at how https://github.com/bolt/GoogleAnalytics has done it, since this extension does not add any widget I don't think it will be much help to you.

**Comment by Narjhanam** [comment]
I will check it out.
Thank you SahAssar for your time and input.
Cheers :beers:
